using System.Collections.Immutable;
using System.Text;

namespace RKSoftware.Packages.ApiRequestValidation.SourceGenerator;

public static class ApiRequestValidationSourceGeneratorHelper
{
    public static string GenerateValidatorRegistrationsClass(ImmutableArray<ValidatorToRegister?> validators)
    {
        if (validators == null)
        {
            throw new ArgumentNullException(nameof(validators));
        }

        var generatedClass = $@"
// <auto-generated> UTC: {DateTime.UtcNow}
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using FluentValidation;
            
namespace RKSoftware.Packages.ApiRequestValidation
{{
    public static partial class ValidatorRegistrations
    {{
        public static void AddValidators(this IServiceCollection services)
        {{
            if (services is null)
            {{
                throw new ArgumentNullException(nameof(services));
            }}
            {GenerateValidatorRegistrations(validators)}
        }}
    }}
}}";

        return generatedClass;
    }

    private static string GenerateValidatorRegistrations(ImmutableArray<ValidatorToRegister?> validators)
    {
        var method = new StringBuilder();
        foreach (var validator in validators)
        {
            if(validator == null)
            {
                continue;
            }
            method.AppendLine($@"services.AddScoped<IValidator<{validator.Value.ClassNameToValidate}>, {validator.Value.ValidatorName}>();");
            
        }

        return method.ToString();
    }
}
